######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 25 20:01:41 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.hpp
SOURCES += main.cpp window.cpp
