######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 2 21:42:52 2015
######################################################################

TEMPLATE = app
TARGET = ct
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ct.hpp day.hpp db.hpp food.hpp meal.hpp user.hpp
SOURCES += ct.cpp day.cpp db.cpp food.cpp meal.cpp testing.cpp user.cpp
